=== JornWildt/Fablescript/Src/Core/Fablescript.Core/Fablescript/Fablescript.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="https://fablescript.org/schema/core"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:html="http://www.w3.org/1999/xhtml"
           xmlns:m="https://fablescript.org/schema/core">

  <xs:element name="Fable" type="m:FableType"/>

  <xs:complexType name="FableType">
    <xs:annotation>
      <xs:documentation>
        <div xmlns="http://www.w3.org/1999/xhtml">
          <p>This is the root element for the fable definition file.</p>
        </div>
      </xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="Title" type="xs:string" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            <html:p>Title of this fable.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Description" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            <html:p>Description of this fable.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="InitialLocation" type="m:IdentifierString" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            <html:p>Initial player location name.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Locations" type="m:LocationsType" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            <html:p>Locations</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:all>
  </xs:complexType>


  <xs:complexType name="LocationsType">
    <xs:annotation>
      <xs:documentation>
        <div xmlns="http://www.w3.org/1999/xhtml">
          <p>List of locations in the game.</p>
        </div>
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Location" type="m:LocationType" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>
            <html:p>Single location.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="LocationType">
    <xs:annotation>
      <xs:documentation>
        <div xmlns="http://www.w3.org/1999/xhtml">
          <p>Definition of single location.</p>
        </div>
      </xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="Name" type="m:IdentifierString" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            <html:p>Name of this location. Used for internal references.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Title" type="xs:string" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            <html:p>Descriptive title for this location.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Introduction" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            <html:p>Introduction to this location. Will only be shown first time the player enters the location.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Facts" type="m:FactsType" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            <html:p>Facts.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Exits" type="m:ExitsType" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            <html:p>Exits.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:all>
  </xs:complexType>


  <xs:complexType name="FactsType">
    <xs:annotation>
      <xs:documentation>
        <div xmlns="http://www.w3.org/1999/xhtml">
          <p>List of facts applying to the current location.</p>
        </div>
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Fact" type="m:FactType" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>
            <html:p>Single fact.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="FactType">
    <xs:annotation>
      <xs:documentation>
        <div xmlns="http://www.w3.org/1999/xhtml">
          <p>Definition of single fact about a location.</p>
        </div>
      </xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="Text" type="xs:string" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            <html:p>Fact text.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:all>
  </xs:complexType>


  <xs:complexType name="ExitsType">
    <xs:annotation>
      <xs:documentation>
        <div xmlns="http://www.w3.org/1999/xhtml">
          <p>List of exits for the current location.</p>
        </div>
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Exit" type="m:ExitType" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>
            <html:p>Single exit.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="ExitType">
    <xs:annotation>
      <xs:documentation>
        <div xmlns="http://www.w3.org/1999/xhtml">
          <p>Definition of single exit at a location.</p>
        </div>
      </xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="Name" type="m:IdentifierString" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            <html:p>Name of this exit. Used for internal references.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Title" type="xs:string" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            <html:p>Descriptive title for this exit.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Description" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            <html:p>Full description of this exit.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TargetLocationName" type="m:IdentifierString" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            <html:p>Name of the location this exit leads to.</html:p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:all>
  </xs:complexType>

  
  <xs:simpleType name="IdentifierString">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z][a-zA-Z0-9_]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== JornWildt/Fablescript/Fables/Jokull/main.xml
<?xml version="1.0" encoding="utf-8" ?>
<Fable xmlns="https://fablescript.org/schema/core"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://fablescript.org/schema/core ../../Src/Core/Fablescript.Core/Fablescript/Fablescript.xsd">
  <Title>Jokull</Title>
  <Description>A story of ice and mystery.</Description>
  <InitialLocation>BlackBeach</InitialLocation>
  <Locations>
    <Location>
      <Name>BlackBeach</Name>
      <Title>Black sand beach</Title>
      <Introduction>You find yourself resting on the sand with no rememberence of how you came here or who you are.</Introduction>
      <Facts>
        <Fact>
          <Text>The beach stretches as far as you can see to the east and west.</Text>
        </Fact>
        <Fact>
          <Text>Black sand covers all the beach.</Text>
        </Fact>
        <Fact>
          <Text>The sea is calm and stretches to infinity without interruptions.</Text>
        </Fact>
        <Fact>
          <Text>Soft mountains rises in the distance to the north. A huge glacier tops the central mountain.</Text>
        </Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>East</Name>
          <Title>East</Title>
          <Description>The beach stretches to the east.</Description>
          <TargetLocationName>BlackBeachEast</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>BlackBeachEast</Name>
      <Title>Eastern end of black sand beach</Title>
      <Facts>
        <Fact>
          <Text>The beach stretches as far as you can see to the west.</Text>
        </Fact>
        <Fact>
          <Text>Cliffs rises in the east.</Text>
        </Fact>
        <Fact>
          <Text>Black sand covers all the beach.</Text>
        </Fact>
        <Fact>
          <Text>The sea is calm and stretches to infinity without interruptions.</Text>
        </Fact>
        <Fact>
          <Text>Soft mountains rises in the distance to the north. A huge glacier tops the central mountain.</Text>
        </Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>West</Name>
          <Title>West</Title>
          <Description>The beach stretches to the west.</Description>
          <TargetLocationName>BlackBeach</TargetLocationName>
        </Exit>
        <Exit>
          <Name>East</Name>
          <Title>East</Title>
          <Description>A gentle slope leads uphill to the top of the cliffs.</Description>
          <TargetLocationName>Cliffs</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>Cliffs</Name>
      <Title>The cliffs</Title>
      <Facts>
        <Fact>
          <Text>On a remote peninsula where high cliffs meet the sea.</Text>
        </Fact>
        <Fact>
          <Text>Cries from distant shalkren floating on the wind can be heard.</Text>
        </Fact>
        <Fact>
          <Text>At the edge of the cliffs a small Tervuun nests.</Text>
        </Fact>
        <Fact>
          <Text>A smell of old fish fills the air.</Text>
        </Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>West</Name>
          <Title>West</Title>
          <Description>A gentle slope leads west to the black beach.</Description>
          <TargetLocationName>BlackBeachEast</TargetLocationName>
        </Exit>
      </Exits>
    </Location>
  </Locations>
</Fable>

=== JornWildt/Fablescript/Fables/Crypt/main.xml
<?xml version="1.0" encoding="utf-8"?>
<Fable xmlns="https://fablescript.org/schema/core"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://fablescript.org/schema/core ../../Src/Core/Fablescript.Core/Fablescript/Fablescript.xsd">
  <Title>Crypt of Shadows</Title>
  <Description>An ancient crypt filled with darkness, puzzles, and lurking evil.</Description>
  <InitialLocation>EntranceHall</InitialLocation>

  <Locations>
    <Location>
      <Name>EntranceHall</Name>
      <Title>Entrance Hall</Title>
      <Introduction>You stand at the heavy stone doors of an ancient crypt. The air is stale, and torchlight flickers weakly.</Introduction>
      <Facts>
        <Fact><Text>The stone walls are covered in moss and faded carvings.</Text></Fact>
        <Fact><Text>A broken statue lies near the entrance, its eyes hollow.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>North</Name>
          <Title>North</Title>
          <Description>A dark corridor leads deeper into the crypt.</Description>
          <TargetLocationName>GuardianChamber</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>GuardianChamber</Name>
      <Title>Guardian Chamber</Title>
      <Facts>
        <Fact><Text>Large skeletal remains lie scattered across the stone floor.</Text></Fact>
        <Fact><Text>Two massive stone doors block passage north and east.</Text></Fact>
        <Fact><Text>A glowing glyph pulses on the floor in the center of the room.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>South</Name>
          <Title>South</Title>
          <Description>The entrance hall lies to the south.</Description>
          <TargetLocationName>EntranceHall</TargetLocationName>
        </Exit>
        <Exit>
          <Name>North</Name>
          <Title>North</Title>
          <Description>A heavy stone door leads to a burial chamber.</Description>
          <TargetLocationName>BurialChamber</TargetLocationName>
        </Exit>
        <Exit>
          <Name>East</Name>
          <Title>East</Title>
          <Description>An arched hallway leads toward the puzzle room.</Description>
          <TargetLocationName>PuzzleRoom</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>BurialChamber</Name>
      <Title>Burial Chamber</Title>
      <Facts>
        <Fact><Text>Sarcophagi line the walls, some open, some sealed.</Text></Fact>
        <Fact><Text>The scent of ancient decay clings to the air.</Text></Fact>
        <Fact><Text>Scratches suggest something once crawled out of one of the tombs.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>South</Name>
          <Title>South</Title>
          <Description>The Guardian Chamber lies to the south.</Description>
          <TargetLocationName>GuardianChamber</TargetLocationName>
        </Exit>
        <Exit>
          <Name>East</Name>
          <Title>East</Title>
          <Description>A narrow passage leads east toward a hidden vault.</Description>
          <TargetLocationName>HiddenVault</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>HiddenVault</Name>
      <Title>Hidden Vault</Title>
      <Facts>
        <Fact><Text>Gold glitters in piles, but several chests lie broken and empty.</Text></Fact>
        <Fact><Text>A skeleton in ornate armor slumps near the back wall.</Text></Fact>
        <Fact><Text>A locked iron door bars access to another room to the south.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>West</Name>
          <Title>West</Title>
          <Description>The burial chamber lies west.</Description>
          <TargetLocationName>BurialChamber</TargetLocationName>
        </Exit>
        <Exit>
          <Name>South</Name>
          <Title>South</Title>
          <Description>A locked door leads to the Ritual Circle.</Description>
          <TargetLocationName>RitualCircle</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>PuzzleRoom</Name>
      <Title>Puzzle Room</Title>
      <Facts>
        <Fact><Text>Four pillars each bear a strange symbol: sun, moon, flame, and shadow.</Text></Fact>
        <Fact><Text>The room hums faintly with magical energy.</Text></Fact>
        <Fact><Text>Stepping on the wrong tiles causes the floor to shake violently.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>West</Name>
          <Title>West</Title>
          <Description>The Guardian Chamber is to the west.</Description>
          <TargetLocationName>GuardianChamber</TargetLocationName>
        </Exit>
        <Exit>
          <Name>East</Name>
          <Title>East</Title>
          <Description>A shimmering portal pulses at the far end of the room.</Description>
          <TargetLocationName>CrystalCavern</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>CrystalCavern</Name>
      <Title>Crystal Cavern</Title>
      <Facts>
        <Fact><Text>Vast crystals protrude from the floor and ceiling, glowing faintly.</Text></Fact>
        <Fact><Text>The hum of magic is almost deafening here.</Text></Fact>
        <Fact><Text>A massive shadowy creature watches you from the darkness.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>West</Name>
          <Title>West</Title>
          <Description>A shimmering portal leads back to the puzzle room.</Description>
          <TargetLocationName>PuzzleRoom</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>RitualCircle</Name>
      <Title>Ritual Circle</Title>
      <Facts>
        <Fact><Text>A blood-stained circle is etched into the stone floor.</Text></Fact>
        <Fact><Text>Candles flicker despite the absence of wind.</Text></Fact>
        <Fact><Text>Dark chanting echoes faintly though no one is visible.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>North</Name>
          <Title>North</Title>
          <Description>The vault lies north through the locked door.</Description>
          <TargetLocationName>HiddenVault</TargetLocationName>
        </Exit>
        <Exit>
          <Name>South</Name>
          <Title>South</Title>
          <Description>A tunnel leads down into the dungeon depths.</Description>
          <TargetLocationName>DungeonDepths</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>DungeonDepths</Name>
      <Title>Dungeon Depths</Title>
      <Facts>
        <Fact><Text>The walls are damp and covered in claw marks.</Text></Fact>
        <Fact><Text>Growls and the sound of shuffling echo through the dark.</Text></Fact>
        <Fact><Text>Something ancient and powerful stirs here.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>North</Name>
          <Title>North</Title>
          <Description>A tunnel leads up to the ritual circle.</Description>
          <TargetLocationName>RitualCircle</TargetLocationName>
        </Exit>
      </Exits>
    </Location>
  </Locations>

  <Objects>
    <Object>
      <Name>AncientKey</Name>
      <Title>Ancient Key</Title>
      <Description>An iron key covered in runes. It feels warm to the touch.</Description>
      <Location>GuardianChamber</Location>
    </Object>

    <Object>
      <Name>SapphireAmulet</Name>
      <Title>Sapphire Amulet</Title>
      <Description>An amulet with a glowing blue gem. Protects against shadow magic.</Description>
      <Location>CrystalCavern</Location>
    </Object>

    <Object>
      <Name>HealingPotion</Name>
      <Title>Healing Potion</Title>
      <Description>A small vial of red liquid. Restores vitality when consumed.</Description>
      <Location>BurialChamber</Location>
    </Object>

    <Object>
      <Name>SilverBlade</Name>
      <Title>Silver Blade</Title>
      <Description>A finely crafted sword with ancient markings. Especially effective against undead.</Description>
      <Location>HiddenVault</Location>
    </Object>
  </Objects>
</Fable>

=== JornWildt/Fablescript/Fables/Techspire/main.xml
<?xml version="1.0" encoding="utf-8"?>
<Fable xmlns="https://fablescript.org/schema/core"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://fablescript.org/schema/core ../../Src/Core/Fablescript.Core/Fablescript/Fablescript.xsd">
  <Title>Techspire HQ</Title>
  <Description>A day in the life at a bustling IT company headquarters.</Description>
  <InitialLocation>Lobby</InitialLocation>

  <Locations>
    <Location>
      <Name>Lobby</Name>
      <Title>Building Lobby</Title>
      <Introduction>You step into the modern lobby of Techspire HQ.</Introduction>
      <Facts>
        <Fact><Text>Clean white walls and minimalist furniture surround you.</Text></Fact>
        <Fact><Text>A receptionist desk stands to the north, unoccupied.</Text></Fact>
        <Fact><Text>A security camera silently rotates above the entrance.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>North</Name>
          <Title>North</Title>
          <Description>Glass doors lead into the main office floor.</Description>
          <TargetLocationName>MainOffice</TargetLocationName>
        </Exit>
        <Exit>
          <Name>East</Name>
          <Title>East</Title>
          <Description>A door labeled 'Break Room'.</Description>
          <TargetLocationName>BreakRoom</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>MainOffice</Name>
      <Title>Main Office Floor</Title>
      <Facts>
        <Fact><Text>Rows of desks with monitors, cables, and coffee mugs.</Text></Fact>
        <Fact><Text>The hum of computers fills the air.</Text></Fact>
        <Fact><Text>Some screens show code, others display spreadsheets.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>South</Name>
          <Title>South</Title>
          <Description>Back to the lobby.</Description>
          <TargetLocationName>Lobby</TargetLocationName>
        </Exit>
        <Exit>
          <Name>North</Name>
          <Title>North</Title>
          <Description>A hallway leads to the server room.</Description>
          <TargetLocationName>ServerRoom</TargetLocationName>
        </Exit>
        <Exit>
          <Name>West</Name>
          <Title>West</Title>
          <Description>A door labeled 'Meeting Room 1'.</Description>
          <TargetLocationName>MeetingRoom1</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>BreakRoom</Name>
      <Title>Break Room</Title>
      <Facts>
        <Fact><Text>A coffee machine gurgles next to a fridge full of energy drinks.</Text></Fact>
        <Fact><Text>A couch and a ping pong table occupy the center.</Text></Fact>
        <Fact><Text>The smell of microwaved meals lingers in the air.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>West</Name>
          <Title>West</Title>
          <Description>Back to the lobby.</Description>
          <TargetLocationName>Lobby</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>ServerRoom</Name>
      <Title>Server Room</Title>
      <Facts>
        <Fact><Text>Rows of blinking servers stand tall behind locked racks.</Text></Fact>
        <Fact><Text>A low hum and a blast of cold air greet you.</Text></Fact>
        <Fact><Text>A warning sign reads: "Authorized Personnel Only".</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>South</Name>
          <Title>South</Title>
          <Description>Return to the main office floor.</Description>
          <TargetLocationName>MainOffice</TargetLocationName>
        </Exit>
        <Exit>
          <Name>East</Name>
          <Title>East</Title>
          <Description>A narrow door marked 'IT Storage'.</Description>
          <TargetLocationName>ITStorage</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>ITStorage</Name>
      <Title>IT Storage Closet</Title>
      <Facts>
        <Fact><Text>Stacks of old monitors and tangled cables clutter the room.</Text></Fact>
        <Fact><Text>An old printer sits unplugged in a corner.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>West</Name>
          <Title>West</Title>
          <Description>Back to the server room.</Description>
          <TargetLocationName>ServerRoom</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>MeetingRoom1</Name>
      <Title>Meeting Room Alpha</Title>
      <Facts>
        <Fact><Text>A large table and a wall-mounted display dominate the room.</Text></Fact>
        <Fact><Text>Sticky notes and whiteboard scribbles from a recent meeting are still visible.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>East</Name>
          <Title>East</Title>
          <Description>Return to the main office floor.</Description>
          <TargetLocationName>MainOffice</TargetLocationName>
        </Exit>
        <Exit>
          <Name>North</Name>
          <Title>North</Title>
          <Description>A hallway leads to the HR office.</Description>
          <TargetLocationName>HRDepartment</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>HRDepartment</Name>
      <Title>HR Department</Title>
      <Facts>
        <Fact><Text>Soft music plays faintly in the background.</Text></Fact>
        <Fact><Text>A bulletin board with company policies hangs on one wall.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>South</Name>
          <Title>South</Title>
          <Description>Back to Meeting Room Alpha.</Description>
          <TargetLocationName>MeetingRoom1</TargetLocationName>
        </Exit>
        <Exit>
          <Name>East</Name>
          <Title>East</Title>
          <Description>A short corridor leads to the CEO's office.</Description>
          <TargetLocationName>CEOOffice</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>CEOOffice</Name>
      <Title>CEO's Office</Title>
      <Facts>
        <Fact><Text>Large glass windows overlook the city skyline.</Text></Fact>
        <Fact><Text>A minimalist desk holds a sleek laptop and a succulent.</Text></Fact>
        <Fact><Text>A shelf of awards lines one wall.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>West</Name>
          <Title>West</Title>
          <Description>Return to the HR department.</Description>
          <TargetLocationName>HRDepartment</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>TestingLab</Name>
      <Title>QA Testing Lab</Title>
      <Facts>
        <Fact><Text>Workstations with dual monitors and testing devices fill the room.</Text></Fact>
        <Fact><Text>Posters of bug life cycles and QA workflows are pinned to the walls.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>West</Name>
          <Title>West</Title>
          <Description>Doorway to the Main Office Floor.</Description>
          <TargetLocationName>MainOffice</TargetLocationName>
        </Exit>
      </Exits>
    </Location>

    <Location>
      <Name>Rooftop</Name>
      <Title>Office Rooftop</Title>
      <Facts>
        <Fact><Text>The rooftop offers a panoramic view of the tech district.</Text></Fact>
        <Fact><Text>Employees sometimes come here to relax or take phone calls.</Text></Fact>
      </Facts>
      <Exits>
        <Exit>
          <Name>Down</Name>
          <Title>Down</Title>
          <Description>Stairs lead down into the break room area.</Description>
          <TargetLocationName>BreakRoom</TargetLocationName>
        </Exit>
      </Exits>
    </Location>
  </Locations>

  <Objects>
    <Object>
      <Name>Keycard</Name>
      <Title>Employee Keycard</Title>
      <Description>A plastic badge labeled "Techspire - Level 3 Access".</Description>
      <Location>Lobby</Location>
    </Object>
  </Objects>
</Fable>
